# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentsmeshRunner < Formula
  desc "AgentsMesh Runner - AI Agent Task Executor"
  homepage "https://agentsmesh.ai"
  version "0.10.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgentsMesh/AgentsMesh/releases/download/v0.10.13/agentsmesh-runner_0.10.13_darwin_amd64.tar.gz"
      sha256 "0ddbc9f5412fbd131edb0e70763e0a5c89a3df93f5de9d8641818aeec4d80f02"

      define_method(:install) do
        bin.install "agentsmesh-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgentsMesh/AgentsMesh/releases/download/v0.10.13/agentsmesh-runner_0.10.13_darwin_arm64.tar.gz"
      sha256 "a15f2caec4ffb78ce107f088c99b99972f374b2e47e3e0bc534869c7c4169d0c"

      define_method(:install) do
        bin.install "agentsmesh-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentsMesh/AgentsMesh/releases/download/v0.10.13/agentsmesh-runner_0.10.13_linux_amd64.tar.gz"
      sha256 "ea5a8c6f89d0fdbe84604e581e35e1f4068b3b2a8cecac4f672aaff0ad89f33b"
      define_method(:install) do
        bin.install "agentsmesh-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentsMesh/AgentsMesh/releases/download/v0.10.13/agentsmesh-runner_0.10.13_linux_arm64.tar.gz"
      sha256 "ae07792d31b84d248ae766be0632ab0c8eaefc364469cd0d6487099d3f76f216"
      define_method(:install) do
        bin.install "agentsmesh-runner"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with AgentsMesh Runner:

      1. Register the runner with your AgentsMesh server:
         # Global: https://agentsmesh.ai (or your own server address)
         agentsmesh-runner register --server <SERVER_URL> --token YOUR_TOKEN

      2. Start the runner:
         agentsmesh-runner run

      For more information, visit: https://agentsmesh.ai/docs/runner
    EOS
  end

  test do
    system "#{bin}/agentsmesh-runner", "version"
  end
end
