# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentsmeshRunner < Formula
  desc "AgentsMesh Runner - AI Agent Task Executor"
  homepage "https://agentsmesh.ai"
  version "0.2.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.11/agentsmesh-runner_0.2.11_darwin_amd64.tar.gz"
      sha256 "3d2a31066aec0e9efaa095503e7df0b774703a9c079969c36e507af9f2f54b59"

      def install
        bin.install "runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.11/agentsmesh-runner_0.2.11_darwin_arm64.tar.gz"
      sha256 "96c640a64055cbb9efc47877ff6f99c2e00db7c13bbe4f950d5494e8098c1f08"

      def install
        bin.install "runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.11/agentsmesh-runner_0.2.11_linux_amd64.tar.gz"
      sha256 "84bcba0b3282710eb2addbcdfabe9c494ff087ad6f94e0cacc43b54e36001fec"
      def install
        bin.install "runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.11/agentsmesh-runner_0.2.11_linux_arm64.tar.gz"
      sha256 "f188c6b55c8629b3c416ec0c539b0f7e12c60429cd4521e8f56b96e37a6395df"
      def install
        bin.install "runner"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with AgentsMesh Runner:

      1. Register the runner with your AgentsMesh server:
         runner register --server https://api.agentsmesh.ai --token YOUR_TOKEN

      2. Start the runner:
         runner run

      For more information, visit: https://agentsmesh.ai/docs/runner
    EOS
  end

  test do
    system "#{bin}/runner", "version"
  end
end
