# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentsmeshRunner < Formula
  desc "AgentsMesh Runner - AI Agent Task Executor"
  homepage "https://agentsmesh.ai"
  version "0.2.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.15/agentsmesh-runner_0.2.15_darwin_amd64.tar.gz"
      sha256 "4a0ae590e9dc21484913467c83c7d0a837a65b505123064b0cd8234ec11d3c3f"

      def install
        bin.install "runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.15/agentsmesh-runner_0.2.15_darwin_arm64.tar.gz"
      sha256 "19d1e8e6adc4b998adfc3f157998f54d2961bfb59b521654d29a1882e25ca3a5"

      def install
        bin.install "runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.15/agentsmesh-runner_0.2.15_linux_amd64.tar.gz"
      sha256 "bf0d0513c8fa25d0d9653abe6dd2a1bb3c974ea47dac1030770f8a3ced0c4c91"
      def install
        bin.install "runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentsMesh/AgentsMeshRunner/releases/download/v0.2.15/agentsmesh-runner_0.2.15_linux_arm64.tar.gz"
      sha256 "43c5de497c2bf347b13bda0801925acc77bf9b2b81b63356b9e8a60163d0445a"
      def install
        bin.install "runner"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with AgentsMesh Runner:

      1. Register the runner with your AgentsMesh server:
         runner register --server https://api.agentsmesh.ai --token YOUR_TOKEN

      2. Start the runner:
         runner run

      For more information, visit: https://agentsmesh.ai/docs/runner
    EOS
  end

  test do
    system "#{bin}/runner", "version"
  end
end
